include:
  - project: 'widas/codequality'
    ref: master
    file: 'ci_templates/go_lib.gitlab-ci.yml'
    
  - project: 'widas/codequality'
    ref: master
    file: 'ci_templates/go_release.gitlab-ci.yml'

stages:
  - prepare
  - test
  - pre_release
  - release

