include:
  - project: 'widas/codequality'
    ref: master
    file: 'ci_templates/go.gitlab-ci.yml'

stages:
  - prepare
  - test
  - build
  - pre_release
  - release
  - package

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

test:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -v -cover $(go list ./... | grep -v /vendor/)

