image: golang:latest

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  # Please edit to your GitLab project
  REPO_NAME: https://gitlab.widas.de/cidaas-public-devkits/cidaas-interceptors/cidaas-go-interceptor

stages:
  - test

test:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -v -cover $(go list ./... | grep -v /vendor/)

artifacts:
    reports:
      sast: gl-sast-report.json

