include:
  - project: 'widas/codequality'
    ref: master
    file: 'ci_templates/go_lib.gitlab-ci.yml'
  - project: 'cidaas-management/cidaas-versioning-ci-templates'
    ref: feature/add-generic-release-yml
    file: 'generic-release.yml'

stages:
  - prepare
  - test
  - build
  - release

get_timestamp:
  image: alpine:latest
  stage: prepare
  script:
    - echo "PACKAGE_VERSION="$(cat version.txt) >> deploy.env
  artifacts:
    reports:
      dotenv:
        - deploy.env
